update logger dependency
loft-sh/cluster-api-provider-vcluster pull request #46
Opened 2024-02-20 10:15 UTC by narcis96

2024-02-20 10:34 UTC, ThomasK33 requested changes
The log messages aren't structured logs and as such won't work/display correctly.

You'll need to refactor them to be more like shown here: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/3077-contextual-logging/README.md

2024-02-20 10:34 UTC, ThomasK33 commented on main.go
> +	log, err := logr.NewLoggerWithOptions(logOpts...)
You can write that as:
```go
	log, err := logr.NewLoggerWithOptions(logr.WithComponentName("vcluster-controller"))
```

but I'd recommend also using the env vars for this, so more in the likes of:

```suggestion
	log, err := logr.NewLoggerWithOptions(
	  logr.WithOptionsFromEnv(),
	  logr.WithComponentName("vcluster-controller"),
	)
```

2024-02-20 10:34 UTC, ThomasK33 commented on main.go
> +	log, err := logr.NewLoggerWithOptions(logOpts...)
You're not handling the error here.

2024-02-20 10:57 UTC, ThomasK33 commented on go.mod
> +go 1.21
I think we can also update this to 1.22 here

2024-02-20 11:37 UTC, narcis96 commented on main.go
> +	log, err := logr.NewLoggerWithOptions(logOpts...)
done

2024-02-22 10:09 UTC, ThomasK33 commented on controllers/vcluster_controller.go
> +			"err", err)
Technically it's an error, so we probably should use an error logger here:

```suggestion
		r.Log.Error(err, "error during virtual cluster deploy",
			"namespace", vCluster.Namespace,
			"name", vCluster.Name,
		)
```

2024-02-22 10:11 UTC, ThomasK33 commented on controllers/vcluster_controller.go
> +		r.Log.Info("readiness check failed", "err", err)
```suggestion
		r.Log.V(1).Info("readiness check failed", "err", err)
```

2024-02-22 10:11 UTC, ThomasK33 commented on controllers/vcluster_controller.go
> +		"clusterName", vCluster.Name)
```suggestion
	r.Log.V(1).Info("upgrade virtual cluster helm chart",
		"namespace", vCluster.Namespace,
		"clusterName", vCluster.Name,
	)
```

2024-02-22 10:12 UTC, ThomasK33 commented on controllers/vcluster_controller.go
> +				"clusterName", vCluster.Name)
```suggestion
			r.Log.Info("vclusters patch version defined in .spec.kubernetesVersion field will be ignored, latest supported patch version will be used",
				"namespace", vCluster.Namespace,
				"name", vCluster.Name
			)
```

2024-02-22 10:13 UTC, ThomasK33 commented on controllers/vcluster_controller.go
> +		"values", values)
```suggestion
	r.Log.Info("Deploy virtual cluster",
		"namespace", vCluster.Namespace,
		"name", vCluster.Name,
		"values", values,
	)
```

2024-02-22 10:13 UTC, ThomasK33 commented on controllers/vcluster_controller.go
> +	r.Log.Info("ready check done", "namespace", vCluster.Namespace, "name", vCluster.Name, "duration", time.Since(t))
```suggestion
	r.Log.V(1).Info("ready check done", "namespace", vCluster.Namespace, "name", vCluster.Name, "duration", time.Since(t))
```

2024-02-22 10:14 UTC, ThomasK33 commented on controllers/vcluster_controller.go
> +		"name", name)
```suggestion
	r.Log.V(1).Info("delete vcluster helm release",
		"namespace", namespace,
		"name", name,
	)
```

2024-02-22 10:17 UTC, ThomasK33 commented on pkg/helm/helm.go
> +			"error executing helm")
```suggestion
		klog.TODO().Error(
			err,
			"error executing helm",
			"args", args, 
			"output", string(output),
		)
```

2024-02-22 10:20 UTC, ThomasK33 commented on pkg/helm/secrets.go
> +			klog.InfoS("list: failed to decode release", "err", err)
```suggestion
			klog.FromContext(ctx).Error(err, "list: failed to decode release", "namespace", iteam.Namespace, "name", item.Name)
```

2024-02-22 10:20 UTC, ThomasK33 commented on pkg/helm/secrets.go
> +			klog.InfoS("list: metadata info is empty of release", "name", rls.Name)
```suggestion
			klog.FromContext(ctx).Info("list: metadata info is empty of release", "name", rls.Name)
```

2024-02-22 10:21 UTC, ThomasK33 commented on main.go
> +	}
Some spacing around the top and bottom
```suggestion

	log, err := logr.NewLoggerWithOptions(
		logr.WithOptionsFromEnv(),
		logr.WithComponentName("vcluster-controller"),
	)
	if err != nil {
		setupLog.Error(err, "unable to setup logger")
		os.Exit(1)
	}

```

2024-02-22 10:24 UTC, ThomasK33 commented on pkg/util/conditions/merge.go
> +// nolint: exhaustive
Can we keep the exhaustive check here (remove this nolint comment), and add the following to the line 188?

```go
case v1alpha1.ConditionSeverityNone:
	return 10
```

2024-02-22 17:03 UTC, ThomasK33 approved these changes

2024-02-22 17:04 UTC, merged